version: '3.8'

services:
  mysql:
    build:
      context: ./nacos/build
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "53306:3306"
    env_file:
      - ./nacos/env/mysql.env
    volumes:
      - ./data/middleware/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always
    networks:
      - middleware

  redis:
    image: redis:latest      # 指定构建 Redis 镜像的目录
    container_name: b_redis
    ports:
      - "16379:6379"
    volumes:
      - ./data/middleware/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - middleware
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "7848:7848"
    environment:
      NACOS_AUTH_ENABLE: 'true'
    env_file:
      - ./nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/init.d/application.properties:/home/nacos/conf/application.properties
      - ./nacos/standalone-logs/:/home/nacos/logs
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - middleware
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq_3_8
    restart: always
    # 节点名 rabbit@rabbitserver，不然会去容器ID
    hostname: rabbitserver
    environment:
      # 默认虚拟机名
      RABBITMQ_DEFAULT_VHOST: admin_vhost
      # 用户名
      RABBITMQ_DEFAULT_USER: root
      # 密码
      RABBITMQ_DEFAULT_PASS: devops666
      # 指定自定义插件目录
      RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/middleware/rabbitmq:/var/lib/rabbitmq
      - ./myplugins:/myplugins
    networks:
      - middleware

networks:
  middleware:
    driver: bridge
  blog_network:
    driver: bridge