server:
  port: 8083
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
lab530:
  swagger:
    title: lab530-blog-md2接口文档
    desc: lab530-blog-md2接口文档
    package: com.lab530.md2.controller
feign:
  okhttp:
    enabled: true