server:
  port: 8081
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
lab530:
  db:
    host: 192.168.1.121
    database: blog-md
  swagger:
    title: lab530-blog-md接口文档
    desc: lab530-blog-md接口文档
    package: com.lab530.md.controller
